---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multiarch-initializer
rules:
  - apiGroups:
      - "*"
    resources:
      - pods
    verbs:
      - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multiarch-initializer
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: multiarch-initializer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multiarch-initializer
subjects:
- kind: ServiceAccount
  name: multiarch-initializer
  namespace: kube-system
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  initializers:
    pending: []
  labels:
    app: multiarch-initializer
  name: multiarch-initializer
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: multiarch-initializer
      name: multiarch-initializer
    spec:
      serviceAccountName: multiarch-initializer
      containers:
        - name: multiarch-initializer
          image: jeefy/multiarch_initializer:0.0.1
          imagePullPolicy: Always
          args:
            - "-annotation=initializer.kubernetes.io/multiarch"
            - "-require-annotation=true"
